export type BodyType = 'star' | 'planet' | 'moon' | 'dwarf';

export interface Moon {
    name: string;
    distance: string;
    type: string;
}

export interface PlanetData {
    id: string;
    name: string;
    distanceAU: string;
    briefDescription: string;
    fullDescription: string[];
    textureUrl: string;
    landscapeUrl: string;
    color: string;
    shadowColor: string;
    glowColor: string;
    moons: Moon[];
    bodyType: BodyType;
    stats: {
        diameter?: string;
        distanceFromSun?: string;
        orbitalPeriod?: string;
        rotationPeriod?: string;
        axialTilt?: string;
        temperature?: string;
        gravity?: string;
        density?: string;
        moons?: string;
        rings?: string;
    };
}

export const PLANETS: PlanetData[] = [
    {
        id: 'sun',
        name: 'Sol',
        distanceAU: '0 UA',
        briefDescription: 'A estrela no centro do Sistema Solar. É uma esfera quase perfeita de plasma quente, aquecida à incandescência por reações de fusão nuclear em seu núcleo.',
        fullDescription: [
            'O Sol é a estrela no centro do Sistema Solar. É uma esfera quase perfeita de plasma quente, aquecida à incandescência por reações de fusão nuclear em seu núcleo, que produz radiação eletromagnética, incluindo luz visível.',
            'O Sol é de longe a fonte de energia mais importante para a vida na Terra. Seu diâmetro é de cerca de 1,39 milhão de quilômetros, ou 109 vezes o da Terra. Sua massa é aproximadamente 330.000 vezes a da Terra.',
            'O Sol formou-se há cerca de 4,6 bilhões de anos a partir do colapso gravitacional de matéria dentro de uma grande nuvem molecular. A maior parte dessa matéria se concentrou no centro, enquanto o restante se achatou em um disco orbital que se tornou o Sistema Solar.',
            'O Sol orbita o centro da Via Láctea a uma distância de cerca de 26.000 anos-luz, completando uma revolução em aproximadamente 225 milhões de anos. Sua temperatura superficial é de cerca de 5.500°C, enquanto o núcleo atinge 15 milhões de °C.',
        ],
        textureUrl: 'sun.jpg',
        landscapeUrl: 'sun.jpg',
        color: '#FFD700',
        shadowColor: '#FF8C00',
        glowColor: 'rgba(255, 215, 0, 0.8)',
        moons: [],
        bodyType: 'star',
        stats: {
            diameter: '1.392.700 km',
            distanceFromSun: '0 km (centro)',
            orbitalPeriod: '225 milhões de anos (galáctico)',
            rotationPeriod: '25-35 dias',
            axialTilt: '7,25°',
            temperature: '5.500°C (superfície) / 15.000.000°C (núcleo)',
            gravity: '274 m/s²',
            density: '1.408 kg/m³',
            moons: '8 planetas orbitando',
            rings: 'Não possui',
        },
    },
    {
        id: 'mercury',
        name: 'Mercúrio',
        distanceAU: '0,4 UA',
        briefDescription: 'Mercúrio é o primeiro planeta do sistema solar e também o menor deles, sendo ligeiramente maior do que a Lua, e se encontra fora da zona habitável.',
        fullDescription: [
            'Mercúrio é o primeiro planeta do sistema solar e também o menor deles, sendo ligeiramente maior do que a Lua, e se encontra fora da zona habitável. Seu nome é uma homenagem ao mais veloz dos Deuses Romanos.',
            'Faz parte dos planetas rochosos (também conhecidos como planetas internos) e é composto principalmente de metais e silicatos. Seu núcleo é metálico, feito de ferro. Sua fina exosfera é composta por átomos de oxigênio, sódio, hidrogênio, hélio e potássio, provenientes da superfície atingida pelo vento solar e meteoroides.',
            'Possui inúmeras crateras, que recebem o nome de pessoas famosas. Existem áreas planas e penhascos. Sua cor é marrom-acinzentada. Temperaturas extremas variam entre 430°C e -180°C.',
            'Devido a algumas anomalias em sua órbita, Mercúrio levou à descoberta da Teoria da Relatividade Geral de Einstein, explicando a curvatura do espaço-tempo.',
        ],
        textureUrl: 'mercury.jpg',
        landscapeUrl: 'mercury.jpg',
        color: '#E8927C',
        shadowColor: 'rgba(188, 143, 127, 0.6)',
        glowColor: 'rgba(234, 205, 199, 0.6)',
        moons: [],
        bodyType: 'planet',
        stats: {
            diameter: '4.880 km (raio de 2.440 km)',
            distanceFromSun: '58 milhões de km (0,4 UA)',
            orbitalPeriod: '88 dias',
            rotationPeriod: '59 dias terrestres',
            axialTilt: '~2°',
            temperature: '430°C / -180°C',
            gravity: '3,7 m/s²',
            density: '~13.600 kg/m³',
            moons: '0',
            rings: 'Não possui',
        },
    },
    {
        id: 'venus',
        name: 'Vênus',
        distanceAU: '0,72 UA',
        briefDescription: 'Vênus é o segundo planeta do sistema solar, e se encontra fora da zona habitável. Seu nome vem da antiga deusa romana do amor e da beleza.',
        fullDescription: [
            'Vênus é o segundo planeta do sistema solar, e se encontra fora da zona habitável. Seu nome vem da antiga deusa romana do amor e da beleza. Seu núcleo é composto por ferro e é envolto por um manto rochoso, com uma camada super fina compondo a crosta rochosa externa. Essa camada às vezes muda de forma, dando origem a vulcões.',
            'Sua atmosfera é composta de dióxido de carbono, com algumas nuvens formadas por ácido sulfúrico. A temperatura e a pressão diminuem nas camadas mais altas da atmosfera. Possui vales e montanhas, e milhares de vulcões.',
            'Um dia no planeta dura 243 dias terrestres, enquanto seu período de translação dura apenas 225 dias terrestres. Sua inclinação axial é de 177 graus, sendo considerado "de cabeça para baixo". Temperaturas entre 460°C e 480°C.',
            'Embora muitas pessoas pensem que Mercúrio é o planeta mais quente, esse título vai para Vênus. Isso acontece pelo fato de o planeta ter uma atmosfera capaz de reter o calor do sol de forma muito efetiva, devido aos gases presentes.',
        ],
        textureUrl: 'venus.jpg',
        landscapeUrl: 'venus.jpg',
        color: '#b45d15',
        shadowColor: '#b85a07',
        glowColor: '#ffcb9c',
        moons: [],
        bodyType: 'planet',
        stats: {
            diameter: '12.104 km',
            distanceFromSun: '108 milhões de km (0,72 UA)',
            orbitalPeriod: '225 dias terrestres',
            rotationPeriod: '243 dias terrestres',
            axialTilt: '177°',
            temperature: '460°C - 480°C',
            gravity: '8,87 m/s²',
            density: '5.243 kg/m³',
            moons: '0',
            rings: 'Não possui',
        },
    },
    {
        id: 'earth',
        name: 'Terra',
        distanceAU: '1 UA',
        briefDescription: 'A Terra é o terceiro planeta do sistema solar, e é a única com água líquida na superfície e cujo nome não deriva da mitologia grega ou romana.',
        fullDescription: [
            'A Terra é o terceiro planeta do sistema solar, e é a única com água líquida na superfície e cujo nome não deriva da mitologia grega ou romana. Possui 4 camadas principais: núcleo interno, núcleo externo, manto e crosta terrestre. O núcleo possui ferro e níquel metálicos. O manto é a camada mais externa.',
            'Sua translação dura 365 dias. Sua rotação dura 23 horas e 56 minutos, porém é aproximada para 24 horas, tornando necessário o ano bissexto. Sua órbita é elíptica. A inclinação axial é de 23,5 graus. A atmosfera da Terra é composta por 78% de nitrogênio, 21% de oxigênio e 1% de outros gases, como o dióxido de carbono.',
            'Possui montanhas, vulcões e vales. A litosfera terrestre se divide em grandes placas tectônicas, que causam os terremotos ao se movimentarem de forma brusca. O oceano cobre 71% da superfície terrestre. Temperatura aproximada de -90°C a 55°C.',
            'A gravidade não é igual em todos os lugares. Quanto mais perto do chão, maior é a gravidade, fazendo com que o tempo passe mais devagar. Porém, a diferença é muito sutil, e não é perceptível.',
        ],
        textureUrl: 'earth.jpg',
        landscapeUrl: 'earth.jpg',
        color: '#26daaa',
        shadowColor: '#7894a9',
        glowColor: '#8cbaff',
        moons: [
            { name: 'Lua', distance: 'm', type: 'm' },
        ],
        bodyType: 'planet',
        stats: {
            diameter: '12.756 km',
            distanceFromSun: '150 milhões de km (1 UA)',
            orbitalPeriod: '365 dias',
            rotationPeriod: '23h 56min (~24h)',
            axialTilt: '23,5°',
            temperature: '-90°C a 55°C',
            gravity: '9,81 m/s²',
            density: '5.520 kg/m³',
            moons: '1',
            rings: 'Não possui',
        },
    },
    {
        id: 'moon',
        name: 'Lua',
        distanceAU: '0,00257 UA',
        briefDescription: 'A Lua é o único satélite natural da Terra e o quinto maior do Sistema Solar. É o corpo celeste mais próximo do nosso planeta.',
        fullDescription: [
            'A Lua é o único satélite natural da Terra e o quinto maior satélite natural do Sistema Solar. É o corpo celeste mais próximo do nosso planeta, orbitando a uma distância média de 384.400 km.',
            'Acredita-se que a Lua tenha se formado há cerca de 4,5 bilhões de anos, a partir de detritos resultantes de uma colisão entre a Terra e um corpo do tamanho de Marte chamado Theia. Seu interior é composto por um núcleo de ferro, um manto rochoso e uma crosta.',
            'A Lua não possui atmosfera significativa, o que significa que não há proteção contra meteoroides ou radiação solar. Sua superfície é coberta por crateras, mares de lava solidificada (maria), montanhas e vales. A temperatura na superfície varia de -173°C à noite a 127°C durante o dia.',
            'A Lua influencia as marés terrestres e estabiliza a inclinação do eixo da Terra. Sua gravidade é cerca de 1/6 da terrestre. O mesmo lado da Lua está sempre voltado para a Terra devido à rotação sincronizada.',
        ],
        textureUrl: 'moon.jpg',
        landscapeUrl: 'moon.jpg',
        color: '#C0C0C0',
        shadowColor: '#404040',
        glowColor: 'rgba(192, 192, 192, 0.4)',
        moons: [],
        bodyType: 'moon',
        stats: {
            diameter: '3.474 km',
            distanceFromSun: '384.400 km da Terra',
            orbitalPeriod: '27,3 dias',
            rotationPeriod: '27,3 dias (sincronizada)',
            axialTilt: '6,68°',
            temperature: '-173°C a 127°C',
            gravity: '1,62 m/s²',
            density: '3.344 kg/m³',
            moons: 'N/A (é uma lua)',
            rings: 'Não possui',
        },
    },
    {
        id: 'mars',
        name: 'Marte',
        distanceAU: '1,5 UA',
        briefDescription: 'Marte é o quarto planeta do sistema solar, e o único, além da Terra, com potencial para vida. Seu nome vem do antigo Deus romano da guerra.',
        fullDescription: [
            'Marte é o quarto planeta do sistema solar, e o único, além da Terra, com potencial para vida. Seu nome vem do antigo Deus romano da guerra. Sua composição inclui um núcleo de ferro, níquel e enxofre, envolto por um manto rochoso. A crosta é composta principalmente por basalto.',
            'A rotação de Marte dura apenas 24,6 horas, e sua translação dura 667 dias terrestres. Sua inclinação axial é de 25,19 graus, o que significa que Marte também experimenta estações. A atmosfera é composta principalmente por dióxido de carbono, nitrogênio e argônio.',
            'Suas cores são marrom, dourado e bege, e sua cor avermelhada vem da oxidação do ferro presente no solo. Possui um grande sistema de cânions chamado Valles Marineris. Temperaturas entre -143°C e 35°C. O planeta sofre com tempestades densas de poeira.',
            'O planeta recebeu o nome do deus romano da guerra pelo fato de ter coloração avermelhada, pois o deus Marte seria famoso por adorar destruição e conflitos sangrentos.',
        ],
        textureUrl: 'mars.jpg',
        landscapeUrl: 'mars.jpg',
        color: '#e55f45',
        shadowColor: '#6b261a',
        glowColor: '#e86363',
        moons: [
            { name: 'Deimos', distance: 'd', type: 'd' },
            { name: 'Fobos', distance: 'p', type: 'p' },
        ],
        bodyType: 'planet',
        stats: {
            diameter: '6.780 km (raio de 3.390 km)',
            distanceFromSun: '228 milhões de km (1,5 UA)',
            orbitalPeriod: '667 dias terrestres',
            rotationPeriod: '24,6 horas',
            axialTilt: '25,19°',
            temperature: '-143°C a 35°C',
            gravity: '3,73 m/s²',
            density: '3.930 kg/m³',
            moons: '2',
            rings: 'Não possui',
        },
    },
    {
        id: 'jupiter',
        name: 'Júpiter',
        distanceAU: '5,2 UA',
        briefDescription: 'Júpiter é o quinto planeta do sistema solar, e é também o maior deles. Seu nome é em homenagem ao Rei dos Deuses da Roma Antiga.',
        fullDescription: [
            'Júpiter é o quinto planeta do sistema solar, e é também o maior deles. Seu nome é em homenagem ao Rei dos Deuses da Roma Antiga. Composto principalmente por hidrogênio e hélio. A temperatura aumenta cada vez mais conforme chega ao centro.',
            'Sua rotação dura apenas 9,9 horas, e sua translação dura 12 anos. Sua inclinação axial é de apenas 3,13 graus. É composto principalmente por amônia (gelo de amônia e hidrossulfeto de amônio). As faixas espessas contêm enxofre e fósforo. Possui ciclones polares nos dois polos.',
            'Não possui uma superfície, pois é um planeta principalmente gasoso. Temperaturas entre -145°C e 700°C. Júpiter possui uma grande mancha vermelha, que é uma tempestade que já dura centenas de anos.',
            'Júpiter também funciona como um protetor para a Terra, pois sua alta gravidade evita que muitos asteroides colidam com a Terra. Dados indicam que a Grande Mancha Vermelha está diminuindo.',
        ],
        textureUrl: 'jupiter.jpg',
        landscapeUrl: 'jupiter.jpg',
        color: 'orange',
        shadowColor: 'rgba(188, 143, 127, 0.6)',
        glowColor: 'rgba(234, 205, 199, 0.6)',
        moons: [
            { name: 'Io', distance: 'lop', type: 'lop' },
            { name: 'Europa', distance: 'eu', type: 'eu' },
            { name: 'Ganimedes', distance: 'ga', type: 'ga' },
        ],
        bodyType: 'planet',
        stats: {
            diameter: '139.822 km (raio de 69.911 km)',
            distanceFromSun: '778 milhões de km (5,2 UA)',
            orbitalPeriod: '12 anos',
            rotationPeriod: '9,9 horas',
            axialTilt: '3,13°',
            temperature: '-145°C a 700°C',
            gravity: '24,79 m/s²',
            density: '1.326 kg/m³',
            moons: '95',
            rings: '4',
        },
    },
    {
        id: 'saturn',
        name: 'Saturno',
        distanceAU: '9,5 UA',
        briefDescription: 'Saturno é o sexto planeta do sistema solar, e o segundo maior planeta. É gasoso e se encontra fora da zona habitável.',
        fullDescription: [
            'Saturno é o sexto planeta do sistema solar, e o segundo maior planeta. É gasoso e se encontra fora da zona habitável, sendo considerado um planeta externo. Seu nome vem do Deus romano da agricultura e riqueza, além de ser pai de Júpiter.',
            'Sua composição leva principalmente hidrogênio e hélio. Seu núcleo é denso com ferro e níquel, e cercado por um material rochoso com compostos solidificados pela pressão e calor. O núcleo é envolvido por uma camada de hidrogênio metálico líquido. Sua translação dura 29,4 anos terrestres, enquanto sua rotação dura 10,7 horas.',
            'Coberto com nuvens que parecem linhas. Suas tonalidades são amarelo, marrom e cinza. A pressão é tão grande que é capaz de transformar o gás em líquido na região equatorial. No polo norte, há uma corrente de jato hexagonal, com uma enorme tempestade em seu centro. Temperatura média de -140°C.',
            'Saturno é o único planeta do sistema solar que é menos denso do que a água, ou seja, ele seria capaz de flutuar nela. Possui 7 anéis, cada um orbitando a uma velocidade diferente.',
        ],
        textureUrl: 'saturn.jpg',
        landscapeUrl: 'saturn.jpg',
        color: '#b29d81',
        shadowColor: 'rgba(188, 143, 127, 0.6)',
        glowColor: 'rgba(234, 205, 199, 0.6)',
        moons: [
            { name: 'Titã', distance: 'ti', type: 'ti' },
            { name: 'Dione', distance: 'di', type: 'di' },
            { name: 'Encélado', distance: 'enc', type: 'enc' },
        ],
        bodyType: 'planet',
        stats: {
            diameter: '120.500 km',
            distanceFromSun: '1,4 bilhão de km (9,5 UA)',
            orbitalPeriod: '29,4 anos terrestres',
            rotationPeriod: '10,7 horas',
            axialTilt: '26,73°',
            temperature: '-140°C (média)',
            gravity: '10,44 m/s²',
            density: '687 kg/m³',
            moons: '146',
            rings: '7',
        },
    },
    {
        id: 'uranus',
        name: 'Urano',
        distanceAU: '19 UA',
        briefDescription: 'Urano é o sétimo planeta do sistema solar, e seu nome foi dado em homenagem ao Deus grego do céu.',
        fullDescription: [
            'Urano é o sétimo planeta do sistema solar, e seu nome foi dado em homenagem ao Deus grego do céu. Composto principalmente por água, metano e amônia. Sua coloração azulada vem do metano. É um dos dois planetas gelados. Possui um pequeno núcleo rochoso.',
            'Sua rotação dura 17 horas, e sua translação dura 84 anos. Sua inclinação axial é de 97,77 graus, o que significa que ele praticamente "rola" em sua órbita. Constituída principalmente por hidrogênio, hélio, água, metano e amônia.',
            'Não possui uma superfície, pois é um planeta principalmente gasoso. Temperaturas entre -224°C e -195°C. Urano foi o primeiro planeta que foi descoberto por um telescópio, pois primeiro pensou-se que ele era um cometa.',
            'Urano possui 13 anéis conhecidos e 27 luas confirmadas. Sua atmosfera é a mais fria do sistema solar, com temperatura mínima de -224°C.',
        ],
        textureUrl: 'uranos.jpg',
        landscapeUrl: 'uranos.jpg',
        color: '#8dcdd8',
        shadowColor: 'rgba(127, 188, 171, 0.6)',
        glowColor: 'rgba(234, 205, 199, 0.6)',
        moons: [
            { name: 'Miranda', distance: 'mir', type: 'mir' },
            { name: 'Ariel', distance: 'ari', type: 'ari' },
            { name: 'Umbriel', distance: 'umb', type: 'umb' },
        ],
        bodyType: 'planet',
        stats: {
            diameter: '51.118 km',
            distanceFromSun: '2,9 bilhões de km (19 UA)',
            orbitalPeriod: '84 anos',
            rotationPeriod: '17 horas',
            axialTilt: '97,77°',
            temperature: '-224°C a -195°C',
            gravity: '8,69 m/s²',
            density: '1.270 kg/m³',
            moons: '27',
            rings: '13',
        },
    },
    {
        id: 'neptune',
        name: 'Netuno',
        distanceAU: '30 UA',
        briefDescription: 'Netuno é o oitavo planeta do sistema solar, e seu nome foi dado em homenagem ao Deus romano dos mares.',
        fullDescription: [
            'Netuno é o oitavo planeta do sistema solar, e seu nome foi dado em homenagem ao Deus romano dos mares. Composto principalmente por água, metano e amônia, além de ter um núcleo mais denso e rochoso.',
            'A rotação de Netuno dura 16 horas, enquanto sua translação demora 165 anos. Sua inclinação axial é de 28,32 graus. Possui principalmente hidrogênio e hélio em sua atmosfera. Seus ventos podem ser até 3 vezes mais fortes do que os de Júpiter.',
            'Não possui uma superfície, por ser um planeta gasoso. Porém, seu núcleo rochoso tem uma massa parecida com a da Terra. Temperaturas entre -224°C e -200°C.',
            'Por causa da grande pressão e da presença de metano, acontecem chuvas de diamante no interior do planeta. Netuno foi o primeiro planeta a ter sua existência prevista por cálculos matemáticos antes de ser observado por telescópio.',
        ],
        textureUrl: 'neptune.jpg',
        landscapeUrl: 'neptune.jpg',
        color: '#4f83e2',
        shadowColor: '#2d4153',
        glowColor: 'rgba(234, 205, 199, 0.6)',
        moons: [
            { name: 'Tritão', distance: 'tri', type: 'tri' },
            { name: 'Proteu', distance: 'pro', type: 'pro' },
            { name: 'Nereida', distance: 'ner', type: 'ner' },
        ],
        bodyType: 'planet',
        stats: {
            diameter: '49.244 km',
            distanceFromSun: '4,5 bilhões de km (30 UA)',
            orbitalPeriod: '165 anos',
            rotationPeriod: '16 horas',
            axialTilt: '28,32°',
            temperature: '-224°C a -200°C',
            gravity: '11,15 m/s²',
            density: '1.638 kg/m³',
            moons: '16',
            rings: '5',
        },
    },
    {
        id: 'pluto',
        name: 'Plutão',
        distanceAU: '39 UA',
        briefDescription: 'Plutão é o segundo planeta anão do sistema solar, localizado no cinturão de Kuiper. Seu nome foi dado em homenagem ao deus romano do submundo.',
        fullDescription: [
            'Plutão é o segundo planeta anão do sistema solar, localizado no cinturão de Kuiper (região transnetuniana). Seu nome foi dado em homenagem ao deus romano do submundo. Uma menina de 11 anos escolheu o nome.',
            'Sua translação dura 248 anos, enquanto sua rotação dura 153 horas. Possui um núcleo rochoso, com gelo de água em volta. Composta principalmente por nitrogênio molecular, mas também foram detectadas moléculas de metano e monóxido de carbono.',
            'Possui montanhas, vales e crateras. Ela é revestida por gases como metano e nitrogênio. Seu diâmetro tem 2.377 km, e está a 5,9 bilhões de km do sol. A gravidade baixa faz com que a altitude da atmosfera seja muito extensa.',
            'Plutão já foi o nono planeta do sistema solar, porém foi reclassificado, em 2006, pela União Astronômica Internacional, se tornando um planeta anão, por conta de objetos que podem cruzar sua órbita.',
        ],
        textureUrl: 'pluto.jpg',
        landscapeUrl: 'pluto.jpg',
        color: '#FF8732',
        shadowColor: '#2d4153',
        glowColor: 'rgba(234, 205, 199, 0.6)',
        moons: [],
        bodyType: 'dwarf',
        stats: {
            diameter: '2.377 km',
            distanceFromSun: '5,9 bilhões de km (39 UA)',
            orbitalPeriod: '248 anos',
            rotationPeriod: '153 horas',
            axialTilt: '122,5°',
            temperature: '-233°C a -223°C',
            gravity: '0,62 m/s²',
            density: '1.900 - 2.100 kg/m³',
            moons: '5',
            rings: 'Não possui',
        },
    },
    {
        id: 'ceres',
        name: 'Ceres',
        distanceAU: '2,8 UA',
        briefDescription: 'Ceres é o planeta anão mais próximo da Terra, localizado no cinturão de asteroides, entre Marte e Júpiter.',
        fullDescription: [
            'Ceres é o planeta anão mais próximo da Terra, localizado no cinturão de asteroides, entre Marte e Júpiter, sendo o único dos planetas anões a se localizar no sistema solar interno. Seu nome vem da deusa romana do milho e da colheita.',
            'Sua rotação dura 9 horas, enquanto sua translação, 4,6 anos terrestres. Possui um núcleo sólido e seu manto contém gelo de água. Sua crosta é rochosa e cheia de poeira. É provável que tenha vapor de água em sua atmosfera.',
            'Coberta por crateras pequenas e bem jovens. Está a 413 milhões de km do sol, sendo 2,8 UA. Seu raio é de 476 km.',
            'É o maior objeto localizado no cinturão de asteroides. Foi descoberto em 1801 por Giuseppe Piazzi e reclassificado como planeta anão em 2006.',
        ],
        textureUrl: 'ceres.jpg',
        landscapeUrl: 'ceres.jpg',
        color: '#A0A0A0',
        shadowColor: '#404040',
        glowColor: 'rgba(160, 160, 160, 0.4)',
        moons: [],
        bodyType: 'dwarf',
        stats: {
            diameter: '952 km (raio de 476 km)',
            distanceFromSun: '413 milhões de km (2,8 UA)',
            orbitalPeriod: '4,6 anos terrestres',
            rotationPeriod: '9 horas',
            axialTilt: '~4°',
            temperature: '-105°C (média)',
            gravity: '0,284 m/s²',
            density: '2.200 kg/m³',
            moons: '0',
            rings: 'Não possui',
        },
    },
    {
        id: 'haumea',
        name: 'Haumea',
        distanceAU: '43 UA',
        briefDescription: 'Haumea é o terceiro planeta anão do sistema solar, localizado no cinturão de Kuiper. Seu nome veio da deusa havaiana da fertilidade.',
        fullDescription: [
            'Haumea é o terceiro planeta anão do sistema solar, localizado no cinturão de Kuiper. Seu nome veio da deusa havaiana da fertilidade. Acredita-se que Haumea seja formada por rocha e uma camada de gelo.',
            'Sua translação dura 285 anos, enquanto a rotação dura apenas 4 horas. Não se sabe muito sobre a atmosfera e a superfície de Haumea. Seu diâmetro possui 1.740 km, e está a 6,5 bilhões de km do sol.',
            'Haumea possui um formato oval, por conta da sua velocidade de rotação, que é uma das mais rápidas do sistema solar. Sua densidade é estimada entre 2.600 e 3.300 kg/m³.',
            'Haumea possui dois satélites conhecidos: Hiiaka e Namaka, nomeados em homenagem às filhas da deusa Haumea na mitologia havaiana.',
        ],
        textureUrl: 'haumea.jpg',
        landscapeUrl: 'haumea.jpg',
        color: '#D4C5B0',
        shadowColor: '#5A5040',
        glowColor: 'rgba(212, 197, 176, 0.4)',
        moons: [],
        bodyType: 'dwarf',
        stats: {
            diameter: '~1.740 km',
            distanceFromSun: '6,5 bilhões de km (43 UA)',
            orbitalPeriod: '285 anos',
            rotationPeriod: '4 horas',
            axialTilt: '~126°',
            temperature: '-241°C (estimada)',
            gravity: '~0,401 m/s²',
            density: '2.600 - 3.300 kg/m³',
            moons: '2',
            rings: '1 (descoberto em 2017)',
        },
    },
    {
        id: 'makemake',
        name: 'Makemake',
        distanceAU: '45,8 UA',
        briefDescription: 'Makemake é o quarto planeta anão do sistema solar, localizado no cinturão de Kuiper. Seu nome foi dado em homenagem ao deus Rapanui da fertilidade.',
        fullDescription: [
            'Makemake é o quarto planeta anão do sistema solar, localizado no cinturão de Kuiper. Seu nome foi dado em homenagem ao deus Rapanui da fertilidade. Sua translação leva cerca de 305 anos, enquanto a rotação dura 22 horas e 30 minutos.',
            'Não se sabe muito sobre a estrutura de Makemake. Provavelmente composta por nitrogênio, enquanto está mais próxima do sol (periélio). Foi detectado metano e etano congelados em sua superfície, e aparenta ter uma coloração marrom-avermelhada.',
            'Seu raio possui 715 km, e está a aproximadamente 6,8 bilhões de km do sol, o que corresponde a 45,8 UA. Sua gravidade é estimada em 0,5 m/s².',
            'Makemake é considerada um planeta anão irmão de Plutão, devido a algumas características semelhantes. Possui um satélite conhecido, apelidado de MK2.',
        ],
        textureUrl: 'makemake.jpg',
        landscapeUrl: 'makemake.jpg',
        color: '#C4956A',
        shadowColor: '#5A3A20',
        glowColor: 'rgba(196, 149, 106, 0.4)',
        moons: [],
        bodyType: 'dwarf',
        stats: {
            diameter: '~1.430 km (raio de 715 km)',
            distanceFromSun: '~6,8 bilhões de km (45,8 UA)',
            orbitalPeriod: '~305 anos',
            rotationPeriod: '22h 30min',
            axialTilt: '~29°',
            temperature: '-243°C a -238°C',
            gravity: '~0,5 m/s²',
            density: '1.700 - 2.000 kg/m³',
            moons: '1',
            rings: 'Não possui',
        },
    },
    {
        id: 'eris',
        name: 'Éris',
        distanceAU: '68 UA',
        briefDescription: 'Éris é o quinto e último planeta anão do sistema solar. Seu nome vem da deusa grega da discórdia.',
        fullDescription: [
            'Éris é o quinto e último planeta anão do sistema solar. Seu nome vem da deusa grega da discórdia. Sua translação leva cerca de 557 anos, enquanto sua rotação dura aproximadamente 26 horas.',
            'Não se sabe muito sobre a estrutura de Éris. Por estar muito longe do sol, sua superfície congela e precipita como neve, e ao se aproximar, ela se descongela. Acredita-se que sua superfície seja semelhante à de Plutão.',
            'Seu diâmetro possui 2.400 km, e está a 10 bilhões de km do sol, o que corresponde a 68 UA. Sua gravidade é de 0,82 m/s² e densidade de 2.520 kg/m³.',
            'Seu nome vem da deusa da discórdia, porque a descoberta de Éris fez com que fosse levantada a pauta na comunidade científica sobre o que realmente é um planeta, o que fez com que Plutão fosse reclassificado e perdesse o posto de planeta.',
        ],
        textureUrl: 'eris.jpg',
        landscapeUrl: 'eris.jpg',
        color: '#E0E0E0',
        shadowColor: '#505050',
        glowColor: 'rgba(224, 224, 224, 0.4)',
        moons: [],
        bodyType: 'dwarf',
        stats: {
            diameter: '~2.400 km',
            distanceFromSun: '~10 bilhões de km (68 UA)',
            orbitalPeriod: '~557 anos',
            rotationPeriod: '~26 horas',
            axialTilt: '~44°',
            temperature: '-243°C (estimada)',
            gravity: '0,82 m/s²',
            density: '2.520 kg/m³',
            moons: '1 (Disnomia)',
            rings: 'Não possui',
        },
    },
];
