export type BodyType = 'star' | 'planet' | 'moon' | 'dwarf';

export interface Moon {
    name: string;
    distance: string;
    type: string;
}

export interface PlanetData {
    id: string;
    name: string;
    distanceAU: string;
    briefDescription: string;
    fullDescription: string[];
    textureUrl: string;
    landscapeUrl: string;
    color: string;
    shadowColor: string;
    glowColor: string;
    moons: Moon[];
    bodyType: BodyType;
}

export const PLANETS: PlanetData[] = [
    {
        id: 'sun',
        name: 'Sun',
        distanceAU: '0 AU',
        briefDescription: 'The star at the center of the Solar System. It is a nearly perfect sphere of hot plasma, heated to incandescence by nuclear fusion reactions in its core.',
        fullDescription: [
            'The Sun is the star at the center of the Solar System. It is a nearly perfect sphere of hot plasma, heated to incandescence by nuclear fusion reactions in its core.',
            'The Sun is by far the most important source of energy for life on Earth. Its diameter is about 1.39 million kilometers, or 109 times that of Earth.',
            'The Sun formed about 4.6 billion years ago from the gravitational collapse of matter within a large molecular cloud.',
            'The Sun orbits the center of the Milky Way galaxy at a distance of about 26,000 light-years, completing one revolution in about 225 million years.',
        ],
        textureUrl: '/sun.jpg',
        landscapeUrl: '/sun.jpg',
        color: '#FFD700',
        shadowColor: '#FF8C00',
        glowColor: 'rgba(255, 215, 0, 0.8)',
        moons: [],
        bodyType: 'star',
    },
    {
        id: 'mercury',
        name: 'Mercury',
        distanceAU: '0.39 AU',
        briefDescription: 'The closest planet to the sun. It circles the sun faster than all the other planets, which is why Romans named it after their swift-footed messenger god.',
        fullDescription: [
            'Mercury is the closest planet to the sun. As such, it circles the sun faster than all the other planets, which is why Romans named it after their swift-footed messenger god.',
            'The Sumerians also knew of Mercury since at least 5,000 years ago. It was often associated with Nabu, the god of writing.',
            'A year on Mercury is just 88 days long. One solar day on Mercury lasts the equivalent of 176 Earth days.',
            'Mercury is the smallest planet in the Solar System. It is just 4,879 Kilometres across its equator, compared with 12,742 Kilometres for the Earth.',
        ],
        textureUrl: '/mercury.jpg',
        landscapeUrl: '/mercury.jpg',
        color: '#E8927C',
        shadowColor: 'rgba(188, 143, 127, 0.6)',
        glowColor: 'rgba(234, 205, 199, 0.6)',
        moons: [],
        bodyType: 'planet',
    },
    {
        id: 'venus',
        name: 'Venus',
        distanceAU: '0.723 AU',
        briefDescription: 'Named for the Roman goddess of love and beauty. In ancient times, Venus was often thought to be two different stars, the evening star and the morning star.',
        fullDescription: [
            'Venus, the second planet from the sun, is named for the Roman goddess of love and beauty.',
            'In ancient times, Venus was often thought to be two different stars, the evening star and the morning star.',
            'A day on Venus lasts longer than a year. It takes 243 Earth days to rotate once on its axis.',
            'Atmospheric pressure on Venus is 92 times greater than the Earths.',
        ],
        textureUrl: '/venus.jpg',
        landscapeUrl: '/venus.jpg',
        color: '#b45d15',
        shadowColor: '#b85a07',
        glowColor: '#ffcb9c',
        moons: [],
        bodyType: 'planet',
    },
    {
        id: 'earth',
        name: 'Earth',
        distanceAU: '1 AU',
        briefDescription: 'Earth, our home. It is the only planet known to have an atmosphere containing free oxygen, oceans of liquid water on its surface, and, of course, life.',
        fullDescription: [
            'Earth, our home, is the third planet from the sun. It is the only planet known to have an atmosphere containing free oxygen, oceans of liquid water on its surface, and, of course, life.',
            'The Earths rotation is gradually slowing at approximately 17 milliseconds per hundred years.',
            'The Earth was once believed to be the centre of the universe.',
            'There is only one natural satellite of the planet Earth. As a percentage of the size of the body it orbits, the Moon is the largest satellite of any planet in our solar system.',
        ],
        textureUrl: '/earth.jpg',
        landscapeUrl: '/earth.jpg',
        color: '#26daaa',
        shadowColor: '#7894a9',
        glowColor: '#8cbaff',
        moons: [
            { name: 'Moon', distance: 'm', type: 'm' },
        ],
        bodyType: 'planet',
    },
    {
        id: 'moon',
        name: 'Moon',
        distanceAU: '0.00257 AU',
        briefDescription: 'Earths only natural satellite. It is the fifth largest moon in the Solar System and the largest relative to its parent planet.',
        fullDescription: [
            'The Moon is Earths only natural satellite. It orbits at an average distance of 384,400 km.',
            'The Moon is thought to have formed about 4.51 billion years ago, not long after Earth.',
            'The Moons surface is covered with craters, mountains, valleys, and plains called maria.',
            'The Moon has no atmosphere, no liquid water, and no magnetic field.',
        ],
        textureUrl: '/moon.jpg',
        landscapeUrl: '/moon.jpg',
        color: '#C0C0C0',
        shadowColor: '#404040',
        glowColor: 'rgba(192, 192, 192, 0.4)',
        moons: [],
        bodyType: 'moon',
    },
    {
        id: 'mars',
        name: 'Mars',
        distanceAU: '1.524 AU',
        briefDescription: 'Fourth planet from the Sun and the second smallest planet in the solar system. Named after the Roman god of war often described as the Red Planet.',
        fullDescription: [
            'Mars is the fourth planet from the sun. The Romans named it after their god of war.',
            'Mars and Earth have approximately the same landmass.',
            'Mars is home to the tallest mountain in the solar system. Olympus Mons is 21km high and 600km in diameter.',
            'Mars has the largest dust storms in the solar system. They can last for months and cover the entire planet.',
        ],
        textureUrl: '/mars.jpg',
        landscapeUrl: '/mars.jpg',
        color: '#e55f45',
        shadowColor: '#6b261a',
        glowColor: '#e86363',
        moons: [
            { name: 'Deimos', distance: 'd', type: 'd' },
            { name: 'Phoebos', distance: 'p', type: 'p' },
        ],
        bodyType: 'planet',
    },
    {
        id: 'jupiter',
        name: 'Jupiter',
        distanceAU: '5.203 AU',
        briefDescription: 'Jupiter is the largest planet in the solar system. Fittingly, it was named after the king of the gods in Roman mythology.',
        fullDescription: [
            'Jupiter is the largest planet in the solar system. Fittingly, it was named after the king of the gods in Roman mythology.',
            'Jupiter helped revolutionize the way we saw the universe when Galileo discovered its four large moons in 1610.',
            'Jupiter is the fourth brightest object in the solar system. Only the Sun, Moon and Venus are brighter.',
            'Jupiter has the shortest day of all the planets. It turns on its axis once every 9 hours and 55 minutes.',
        ],
        textureUrl: '/jupiter.jpg',
        landscapeUrl: '/jupiter.jpg',
        color: 'orange',
        shadowColor: 'rgba(188, 143, 127, 0.6)',
        glowColor: 'rgba(234, 205, 199, 0.6)',
        moons: [
            { name: 'Io', distance: 'lop', type: 'lop' },
            { name: 'Europa', distance: 'eu', type: 'eu' },
            { name: 'Ganymede', distance: 'ga', type: 'ga' },
        ],
        bodyType: 'planet',
    },
    {
        id: 'saturn',
        name: 'Saturn',
        distanceAU: '9.539 AU',
        briefDescription: 'Saturn is the sixth planet from the sun and the second largest planet in the solar system. Saturn was the Roman name for Cronus, the lord of the Titans.',
        fullDescription: [
            'Saturn is the sixth planet from the sun and the second largest planet in the solar system.',
            'Saturn is the farthest planet from Earth visible to the naked human eye, but it is through a telescope that the planets most outstanding features can be seen: Saturns rings.',
            'Saturn can be seen with the naked eye. It is the fifth brightest object in the solar system.',
            'Saturn is the flattest planet. Its polar diameter is 90% of its equatorial diameter.',
        ],
        textureUrl: '/saturn.jpg',
        landscapeUrl: '/saturn.jpg',
        color: '#b29d81',
        shadowColor: 'rgba(188, 143, 127, 0.6)',
        glowColor: 'rgba(234, 205, 199, 0.6)',
        moons: [
            { name: 'Titan', distance: 'ti', type: 'ti' },
            { name: 'Dione', distance: 'di', type: 'di' },
            { name: 'Enceladus', distance: 'enc', type: 'enc' },
        ],
        bodyType: 'planet',
    },
    {
        id: 'uranus',
        name: 'Uranus',
        distanceAU: '19.18 AU',
        briefDescription: 'The first planet to be discovered by scientists. The planet is notable for its dramatic tilt, which causes its axis to point nearly directly at the sun.',
        fullDescription: [
            'Uranus is the seventh planet from the sun and the first to be discovered by scientists.',
            'British astronomer William Herschel discovered Uranus accidentally on March 13, 1781.',
            'Uranus turns on its axis once every 17 hours, 14 minutes. The planet rotates in a retrograde direction.',
            'Uranus is often referred to as an ice giant planet.',
        ],
        textureUrl: '/uranos.jpg',
        landscapeUrl: '/uranos.jpg',
        color: '#8dcdd8',
        shadowColor: 'rgba(127, 188, 171, 0.6)',
        glowColor: 'rgba(234, 205, 199, 0.6)',
        moons: [
            { name: 'Miranda', distance: 'mir', type: 'mir' },
            { name: 'Ariel', distance: 'ari', type: 'ari' },
            { name: 'Umbriel', distance: 'umb', type: 'umb' },
        ],
        bodyType: 'planet',
    },
    {
        id: 'neptune',
        name: 'Neptune',
        distanceAU: '30.06 AU',
        briefDescription: 'It was the first planet to get its existence predicted by mathematical calculations before it was actually seen through a telescope on Sept. 23, 1846.',
        fullDescription: [
            'Neptune is the eighth planet from the sun. It was the first planet to get its existence predicted by mathematical calculations.',
            'Only one mission has flown by Neptune Voyager 2 in 1989.',
            'Neptune was not known to the ancients. It is not visible to the naked eye and was first observed in 1846.',
            'Neptune spins on its axis very rapidly. Its equatorial clouds take 18 hours to make one rotation.',
        ],
        textureUrl: '/neptune.jpg',
        landscapeUrl: '/neptune.jpg',
        color: '#4f83e2',
        shadowColor: '#2d4153',
        glowColor: 'rgba(234, 205, 199, 0.6)',
        moons: [
            { name: 'Triton', distance: 'tri', type: 'tri' },
            { name: 'Proteus', distance: 'pro', type: 'pro' },
            { name: 'Nereid', distance: 'ner', type: 'ner' },
        ],
        bodyType: 'planet',
    },
    {
        id: 'pluto',
        name: 'Pluto',
        distanceAU: '39.5 AU',
        briefDescription: 'Pluto, once considered the ninth and most distant planet from the sun, is now the largest known dwarf planet in the solar system.',
        fullDescription: [
            'Pluto, once considered the ninth and most distant planet from the sun, is now the largest known dwarf planet in the solar system.',
            'In 2006, Pluto was reclassified as a dwarf planet, a change widely thought of as a demotion.',
            'Pluto is named after the Greek god of the underworld.',
            'Pluto was reclassified from a planet to a dwarf planet in 2006.',
        ],
        textureUrl: '/pluto.jpg',
        landscapeUrl: '/pluto.jpg',
        color: '#FF8732',
        shadowColor: '#2d4153',
        glowColor: 'rgba(234, 205, 199, 0.6)',
        moons: [],
        bodyType: 'dwarf',
    },
    {
        id: 'ceres',
        name: 'Ceres',
        distanceAU: '2.77 AU',
        briefDescription: 'Ceres is the largest object in the asteroid belt between Mars and Jupiter, and the only dwarf planet located in the inner solar system.',
        fullDescription: [
            'Ceres is the largest object in the asteroid belt between Mars and Jupiter.',
            'It was the first dwarf planet to be visited by a spacecraft, when NASAs Dawn mission arrived in 2015.',
            'Ceres is about 940 kilometers in diameter, making it the largest dwarf planet in the inner solar system.',
            'Scientists believe Ceres may have a subsurface ocean of liquid water.',
        ],
        textureUrl: '/ceres.jpg',
        landscapeUrl: '/ceres.jpg',
        color: '#A0A0A0',
        shadowColor: '#404040',
        glowColor: 'rgba(160, 160, 160, 0.4)',
        moons: [],
        bodyType: 'dwarf',
    },
    {
        id: 'haumea',
        name: 'Haumea',
        distanceAU: '43.13 AU',
        briefDescription: 'Haumea is a dwarf planet located beyond Neptunes orbit. It is notable for its elongated shape and rapid rotation.',
        fullDescription: [
            'Haumea is a dwarf planet located in the Kuiper Belt beyond Neptune.',
            'It has an unusual elongated shape, likely caused by its extremely fast rotation of about 3.9 hours.',
            'Haumea was discovered in 2004 and named after the Hawaiian goddess of fertility.',
            'It has two known moons: Hiiaka and Namaka.',
        ],
        textureUrl: '/haumea.jpg',
        landscapeUrl: '/haumea.jpg',
        color: '#D4C5B0',
        shadowColor: '#5A5040',
        glowColor: 'rgba(212, 197, 176, 0.4)',
        moons: [],
        bodyType: 'dwarf',
    },
    {
        id: 'makemake',
        name: 'Makemake',
        distanceAU: '45.79 AU',
        briefDescription: 'Makemake is a dwarf planet in the Kuiper Belt. It is one of the largest known trans-Neptunian objects.',
        fullDescription: [
            'Makemake is a dwarf planet in the Kuiper Belt, discovered in 2005.',
            'It is named after the Rapa Nui god of fertility.',
            'Makemake has one known moon, nicknamed MK2.',
            'It is the second brightest object in the Kuiper Belt after Pluto.',
        ],
        textureUrl: '/makemake.jpg',
        landscapeUrl: '/makemake.jpg',
        color: '#C4956A',
        shadowColor: '#5A3A20',
        glowColor: 'rgba(196, 149, 106, 0.4)',
        moons: [],
        bodyType: 'dwarf',
    },
    {
        id: 'eris',
        name: 'Eris',
        distanceAU: '67.78 AU',
        briefDescription: 'Eris is the most massive and second-largest known dwarf planet in the solar system. Its discovery led to the reclassification of Pluto.',
        fullDescription: [
            'Eris is the most massive known dwarf planet in the solar system.',
            'Its discovery in 2005 prompted the IAU to formally define the term planet, leading to Plutos reclassification.',
            'Eris is named after the Greek goddess of discord and strife.',
            'It has one known moon, Dysnomia.',
        ],
        textureUrl: '/eris.jpg',
        landscapeUrl: '/eris.jpg',
        color: '#E0E0E0',
        shadowColor: '#505050',
        glowColor: 'rgba(224, 224, 224, 0.4)',
        moons: [],
        bodyType: 'dwarf',
    },
];
